### ISSUE TITLE
box2d vs libbox2d

### ISSUE THREAD

**Issue by helmesjo** [build2-packaging/box2d#1]
More an open question: 
When should one favor prefixing with `lib` to an existing library name (which doesn't have the prefix `lib`), and when should you not? Is [the case mentioned in the HOWTO](https://github.com/build2/HOWTO/blob/master/entries/name-packages-in-project.md) the only case (when the lib you are packaging has both a lib and an executable)?

The thing I imagine being a problem in the future is when it's all mixed up, eg. (for the sake of argument) when _all_ libraries are packaged for build2, but when you go about adding a new dependency (eg. zlib), you never really know if it's prefixed with `lib` (or in that case just reversed to be `libz` which ironically is actually something else) or not, so you always have to look it up beforehand.

**Comment by Rookfighter** [comment]
Hah, a very opinion-based topic. I just asked the same question some time ago: https://github.com/build2-packaging/imgui/pull/2#issuecomment-1148899420

Basically as I understood it: the idiomatic build2 way would be to prefix a pure library package with the `lib` prefix. If the upstream name does not use a lib prefix you can also omit it (given the conditions in the document you linked). Some packages are also mixed with executables and libraries, e.g. the [lua](https://github.com/build2-packaging/lua) package which contains the interpreter as `exe{lua}` and the library as `lib{lua}`. There the package also does not use the lib prefix as it is not a pure library package.
So currently the guideline does not enforce any strict naming convention. It is up to the package contributor to use the prefix or not.
I personally decided to follow the idiomatic guidelines of the project instead of personal preference, which means I use the `lib` prefix ;)
@boris-kolpackov Any additions or corrections?

**Comment by boris-kolpackov** [comment]
No, that's a pretty accurate summary. In fact I would like to copy it into the HOWTO entry if you don't mind.

**Comment by helmesjo** [comment]
Thanks for the answer!
