### ISSUE TITLE
Issues in the submitted 2.4.1 packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/box2d#2]
Noticed a couple of minor issue:

1. In `manifest` the license is specified as `other: MIT`, should be just `MIT` (all three packages).

2. You don't need `depends: libbox2d` in the `-tests` and `-testbed` packages since that's implied by the reverse `tests` and `examples` values in the `libbox2d` `manifest`.

3. Not sure if this is intentional, but `exe{box2d-testbed}` is not marked with `test=true` and so is not executed during the `test` operation.

These are minor so I am pushing the packages to cppget.org, but feel free to publish a revision.

**Comment by Rookfighter** [comment]
Thanks, I will take care of 1. and 2.
Regarding 3.: Actually the testbed is a GUI application (using imgui, hah!) where you can load different physics simulation scenarios, play and interact with them. It is not supposed to be used for automatic testing, AFAIK. That's why I marked it as an example and not test.

**Comment by boris-kolpackov** [comment]
> It is not supposed to be used for automatic testing, AFAIK. That's why I marked it as an example and not test.

Makes sense.

We actually ran into something like this as part of `libQtGui`: how do you test a graphical application? In the end what we did is have a test with a command line option to automatically close the window after a couple of seconds. I am not saying you need to do this here (it will probably require patching upstream) but I thought I would mention it.
